---
- name: Linux Basics Training
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Task Description
      debug:
        msg: "Create file foobar.txt with permission 775"

    - name: Wait for the file creation
      wait_for:
        path: /path/to/your/foobar.txt
        state: file
        mode: '0775'
        timeout: 300  # Adjust the timeout value as needed (in seconds)
        delay: 5

    - name: Check if the file exists
      stat:
        path: /path/to/your/foobar.txt
      register: file_stat_result

    - name: Check file permissions
      assert:
        that:
          - file_stat_result.stat.exists
          - file_stat_result.stat.mode == '0775'
        msg: "File foobar.txt doesn't exist or doesn't have the correct permissions (775)!"

    - name: Display success message
      debug:
        msg: "ok! Task passed!"